language: node_js

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
env:
  matrix:
    secure: fDNu009z7kNvFBmLz2VDYkuE7bak6pXiUnYRYzV0UO9FgOlIw+VqV2uDywqIHi2HkFeJBcTSTYzV6gwDRxCZ0PKjoxE9wzULul5DCf1TCPki3LpPXziLiDIpF4PLzXWx6F553WQcI0z9k89joEP1z/aPuqValIDRycjfNOMQVDIX7ljREpp2sNS263+grZvPppPnYlzWY0RjXZ/f9jpUFoSZQlmzjcRis4wIOr3U6FRgk3he1agqXfia3V9LcIefOb4vmZJ4kNr1kM9HcNHgdbSFTzzG/LHsgEJRNEv04P8rBgkY6p/BWNceYo5YH8tluXXy4TMS2bwy/w1kSUvRma2s0TzpE3PewhOZO2CAkMQ6yD8m3MtSFmA4HjQLHkNgtdEP+Wcz5+MuPo6DdH24gfERAcAT+J4wwo4o9EOIyJvT0pKhsGm6DyuiBQhHwDYAHKdH3+dDWEKY8SpsQQ9xlbIOISwo7iaD3X00dU4bQ0TA8qTslmThrDxAH1l7LU/UCVxpxrknP3fRox9FZJeQy9nlzb3jB6aBTQckvakXihCN7q+KNZMDe2C/udQZ5yl4hW55B/ICzXKRkXboSj1FbI8CXv/jpQXskhrWxARINvkMgEDCnqQk7P9NmUkx20WrJ8YYurXXJTWshORobIRHfE1mPvEDy+A3EFbuqKDWMIA=
